'use client'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import MainView from '@/components/MainLayout/MainContainer'
import { usePathname, useSearchParams } from 'next/navigation'
import { SnackbarProvider } from 'notistack';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pagesWithDefaultLayout = ['/', '/sobre']

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const shouldUseDefaultLayout = pagesWithDefaultLayout.includes(pathname)
  return (
    <html lang="en">
      {shouldUseDefaultLayout ?(
        <SnackbarProvider maxSnack={3}>
            {children}
        </SnackbarProvider>     
      ):(
        <SnackbarProvider maxSnack={3}>
          <MainView>
            {children}
          </MainView>
        </SnackbarProvider>
      )}
    </html>
  )
}
