import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import MainView from '@/app/components/MainLayout/MainContainer'
import GetRoute from '@/app/provider/defaultLayout';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const shouldUseDefaultLayout = <GetRoute/>;

  return (
    <html suppressHydrationWarning lang="en">
      {shouldUseDefaultLayout ?(
          <body>
            {children}   
          </body>
      ):(
        <body>
          <MainView>
            {children}
          </MainView>
        </body>
      )}
    </html>
  )
}
