export type TypePaciente={
    _id?: string,
    DataNascimento: string,
    NumeroCPF: string,
    NumeroRG : string,
    OrgaoEmissor: string,
    NumeroCartaoSUS: string,
    NumeroTituloEleitor: string,
    EleitorUF: string,
    NomePaciente: string,
    NomeSocial: string ,
    Sexo: string,
    Idade: string,
    raca:string,
    cor:string,
    Sangue: string,
    DataCadastro: Date,
    NomePaiouResponsavel: string ,
    NomeMae: string,
    EstadoCivil: string ,
    Endereco: string,
    Bairro: string,
    Cidade: string,
    UF: string,
    CEP: string,
    Referencia: string,
    Celular: [{
        Numero: string,
    }],
    Acompanhantes:[{
      nomeAcompanhante: string,
      numeroCPF: string,
      numeroRG :string,
      DataNascimento: string,
    }],
    Email: string,
    identZona: string,
    TratamentoAtual: string,
    Ocupacao: string,
    GrauEstudo: string,
    Conta: string,
}