export type TypePaciente={
    _id?: number,
    DataNascimento: string,
    NumeroCPF: string,
    NumeroRG : string,
    OrgaoEmissor: string,
    NumeroCartaoSUS: number,
    NumeroTituloEleitor: number,
    EleitorUF: string,
    NomePaciente: string,
    NomeSocial: string ,
    Sexo: string,
    Idade: number,
    raca:string,
    cor:string,
    Sangue: string,
    DataCadastro: string,
    NomePaiouResponsavel: string ,
    NomeMae: string,
    EstadoCivil: string ,
    Endereco: string,
    Bairro: string,
    Cidade: string,
    UF: string,
    CEP: number,
    Referencia: string,
    Celular: [{
        Numero: number,
    }],
    Acompanhantes:[{
      NomeAcompanhante: string,
      NumeroCPF: string,
      NumeroRG:string,
      DataNascimento: string,
    }],
    Email: string,
    identZona: string,
    TratamentoAtual: string,
    Ocupacao: string,
    GrauEstudo: string,
    Conta: number,
}